#!/bin/sh
set -euo pipefail

echo "[linux-busybox-setup] Starting busybox setup"
sleep 0.5

echo "- ./rootfs path: '$INITRAMFS_PATH'"
sleep 0.5

echo "- ./overlay path: '$OVERLAY_PATH'"
sleep 0.5

echo "- ./busybox compilation path: '$BUSY_BOX_PATH'"
sleep 0.5

echo "- ./dependenciess path: '$DEPENDENCIES_PATH'"
sleep 0.5

echo "- ./config path: '$CONFIG_FILES_PATH'"
sleep 0.5

echo "- Opening ./dependencies path"
sleep 0.5

cd $DEPENDENCIES_PATH

if [ ! -d $BUSY_BOX_PATH ]; then
	echo "- Busybox was not found, downloading it.."
	sleep 0.5

	wget https://busybox.net/downloads/busybox-$BUSY_BOX_VERSION.tar.bz2

	echo "- Uncompressing busybox"
	sleep 0.5

	tar -xjf busybox-$BUSY_BOX_VERSION.tar.bz2

	echo "- Moving busybox to it's dependency path"
	sleep 0.5

	mv busybox-$BUSY_BOX_VERSION busybox
else
	echo "- Busybox is already downloaded in dependencies path"
	sleep 0.5
fi

cd $BUSY_BOX_PATH

echo "- Using .config file located in ./config/busybox-config"
sleep 0.5

rm -f .config
cp $CONFIG_FILES_PATH/busybox-config .config

# echo "- Checking if busybox patches for arm64 issues is needed"
# sleep 0.5

# if patch --dry-run --forward -p0 < $PATCHES_PATH/busybox-arm64-shaNI.patch > /dev/null; then
#         echo "- Applying busybox patches"
# 	sleeo 0.5
#         patch -p0 < $PATCHES_PATH/busybox-arm64-shaNI.patch
# else
#         echo "- No busybox patch needed"
# 	sleep 0.5
# fi

if [ "$1" = 'menuconfig' ]; then
        echo "- User requested to open Busybox menu config"
        sleep 0.5

        make menuconfig

        echo "- Applying new configuration into /config/buxybox-config"
        sleep 0.5

        rm -f $CONFIG_FILES_PATH/busybox-config
        cp .config $CONFIG_FILES_PATH/busybox-config

        echo "- Configuration is done"
        sleep 0.5
else
        echo "- Using oldconfig to compile Busybox"
        sleep 0.5

        make oldconfig
fi

echo "- Compiling busybox"
sleep 0.5
make -j$(nproc)

echo "- Installing busybox"
sleep 0.5
make CONFIG_PREFIX=$INITRAMFS_PATH install

echo "- Busybox was installed successfully"
sleep 0.5
