#!/bin/sh
set -euo pipefail

echo "[wolfbear-cleanup] Starting cleanup script"
sleep 0.5

echo "- ./rootfs path: '$INITRAMFS_PATH'"
sleep 0.5

echo "- ./target path: '$TARGET_PATH'"
sleep 0.5

echo "- Is it requested to clean modules kernel cache?: $VAR_KERNEL_MODULES_COMPILE"
sleep 0.5

echo "- Umounting lazy partitions"
sleep 0.5

for fs in proc sys dev; do
  mountpoint -q "$INITRAMFS_PATH/$fs" && sudo umount -l "$INITRAMFS_PATH/$fs"
done

echo "- Cleaning ./rootfs path"
sleep 0.5

sudo rm -rf "$INITRAMFS_PATH"
mkdir -p "$INITRAMFS_PATH"

echo "- Cleaning ./target path"
sleep 0.5

sudo rm -rf $TARGET_PATH
mkdir $TARGET_PATH

if [ "$VAR_KERNEL_MODULES_COMPILE" = 'y']; then
	echo "- Cleaning up modules kernel cache"
	sleep 0.5

	sudo rm -rf $VAR_KERNEL_MODULES_COMPILE
	mkdir $VAR_KERNEL_MODULES_COMPILE
fi

echo "[wolfbear-cleanup] Cleanup is done"
