#! /bin/sh
set -euo pipefail

echo "[wolfbear-rootfs-package] Starting packaging ./rootfs"
sleep 0.5

echo "- ./rootfs path: '$ROOTFS_PATH'"
sleep 0.5

echo "- ./target path: '$TARGET_PATH'"
sleep 0.5

echo "- Umounting lazy partitions (this will be mounted in qemu)"
sleep 0.5

for fs in proc sys dev; do
  mountpoint -q "$INITRAMFS_PATH/$fs" && sudo umount -l "$INITRAMFS_PATH/$fs"
done

echo "- Compressing ./rootfs into initramfs.cpio.gz file"
sleep 0.5

cd $INITRAMFS_PATH
sudo find . -print0 | cpio --null -ov --format=newc | gzip -9 > $TARGET_PATH/initramfs.cpio.gz

echo "[wolfbear-rootfs-package] ./rootfs has been compressed successfully"
sleep 0.5
