#!/bin/sh
set -eu
set -o pipefail 2>/dev/null || true
exit 0
source $WOLFBEAR_INSTALLER_DIR/globals

echo "Uncompressing QT Evertwhere (compiled)"

zstd -dc "$QT_EVERYWHERE_COMPRESSED_FILENAME_DIR" | tar -C "$WOLFBEAR_TARGET_DISK_ROOTFS_MNT_DIR" -xpf -

echo "Decompression finished successfully"