#!/bin/sh
set -euo pipefail

echo "Welcome to wolfbearOS development build script"

PROJECT_PATH=$(pwd)

BUILD_SCRIPTS_PATH=$PROJECT_PATH/scripts
CONFIG_FILES_PATH=$PROJECT_PATH/config
DEPENDENCIES_PATH=$PROJECT_PATH/dependencies
PATCHES_PATH=$PROJECT_PATH/patches
TARGET_PATH=$PROJECT_PATH/target
INITRAMFS_PATH=$PROJECT_PATH/initramfs

LINUX_KERNEL_VERSION=6.1
LINUX_KERNEL_PATH=$DEPENDENCIES_PATH/linux

BUSY_BOX_VERSION=1.37.0
BUSY_BOX_PATH=$DEPENDENCIES_PATH/busybox

OVERLAY_PATH=$PROJECT_PATH/overlay
ROOTFS_PATH=$PROJECT_PATH/rootfs

BUILD_ARCH=arm64
BUILD_CROSS_COMPILE=aarch64-linux-gnu-

OVERLAY_APPS_PATH=$OVERLAY_PATH/apps

# Variables por defecto
VAR_CLEANUP='n'
VAR_COMPILE_LINUX_KERNEL='n'
VAR_COMPILE_LINUX_KERNEL_MENUCONFIG='n'
VAR_COMPILE_BUSYBOX='n'
VAR_BUSYBOX_MENUCONFIG='n'
VAR_INITRAMFS_BUILD='n'
VAR_INITRAMFS_COMPRESS='n'

# Procesar argumentos
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -c|--cleanup)
            VAR_CLEANUP='y'
	    shift
            ;;
        -lk|--linux-kernel)
            VAR_COMPILE_LINUX_KERNEL='y'
            shift
            ;;
        -lc|--linux-menuconfig)
            VAR_COMPILE_LINUX_KERNEL_MENUCONFIG='y'
            shift
            ;;
        -b|--busybox)
            VAR_COMPILE_BUSYBOX='y'
            shift
            ;;
        -bc|--busybox-menuconfig)
            VAR_BUSYBOX_MENUCONFIG='y'
            shift
            ;;
        -ib|--initramfs-build)
            VAR_INITRAMFS_BUILD='y'
            shift
	    ;;
        -ic|--initramfs-compress)
            VAR_INITRAMFS_COMPRESS='y'
            shift
            ;;
    esac
done

mkdir -p $DEPENDENCIES_PATH

if [ "$VAR_CLEANUP" = 'y' ]; then
	echo "[BUILD] Starting cleanup ./rootfs and ./target path"
	sleep 0.5

	cd $BUILD_SCRIPTS_PATH
	source ./wolfbear/wolfbear-cleanup	

	echo "[BUILD] Cleanup finished ./rootfs"
	sleep 0.5
fi

if [ "$VAR_COMPILE_LINUX_KERNEL" = 'y' ]; then
	echo "[BUILD] Compiling and patching linux kernel"
	sleep 0.5

	cd $BUILD_SCRIPTS_PATH
	if [ "$VAR_COMPILE_LINUX_KERNEL_MENUCONFIG" = 'y' ]; then
		source ./linux/linux-kernel-setup menuconfig
	else
		source ./linux/linux-kernel-setup oldconfig
	fi
	echo "[BUILD] Linux kernel was patched successfully"
	sleep 0.5
fi


if [ "$VAR_COMPILE_BUSYBOX" = 'y' ]; then
	echo "[BUILD] Linux busybox setup"
	sleep 0.5

	cd $BUILD_SCRIPTS_PATH
        if [ "$VAR_BUSYBOX_MENUCONFIG" = 'y' ]; then
		source ./linux/linux-busybox-setup menuconfig
        else
		source ./linux/linux-busybox-setup oldconfig
        fi	

	echo "[BUILD] Busybox was compiled successfully"
	sleep 0.5
fi

if [ "$VAR_INITRAMFS_BUILD" = 'y' ]; then
        echo "[BUILD] ./initramfs build started"
        sleep 0.5

        cd $BUILD_SCRIPTS_PATH
        source ./initramfs/initramfs-dependencies-install

        echo "[BUILD] ./initramfs build finished"
        sleep 0.5
fi

if [ "$VAR_INITRAMFS_COMPRESS" = 'y' ]; then
	echo "[BUILD] Strating ./initramfs compression"
	sleep 0.5

	cd $BUILD_SCRIPTS_PATH
	source ./wolfbear/wolfbear-rootfs-package

	echo "[BUILD] Finished ./initramfs compression"
	sleep 0.5
fi

echo "[FINISH] WolfbearOS build script process finished"
sleep 0.2
