#!/bin/bash

echo "Welcome to wolfbearOS development build script"

WOLFBEAR_OS_PROJECT_PATH=$(pwd)

BUILD_SCRIPTS_PATH=$WOLFBEAR_OS_PROJECT_PATH/build-scripts
CONFIG_FILES_PATH=$WOLFBEAR_OS_PROJECT_PATH/config
DEPENDENCIES_PATH=$WOLFBEAR_OS_PROJECT_PATH/dependencies
PATCHES_PATH=$WOLFBEAR_OS_PROJECT_PATH/patches
TARGET_PATH=$WOLFBEAR_OS_PROJECT_PATH/target
INIT_PATH=$WOLFBEAR_OS_PROJECT_PATH/init

LINUX_KERNEL_VERSION=6.1
LINUX_KERNEL_PATH=$DEPENDENCIES_PATH/linux

BUSY_BOX_VERSION=1.37.0
BUSY_BOX_PATH=$DEPENDENCIES_PATH/busybox
BUSY_BOX_CONFIG_PREFIX=$WOLFBEAR_OS_PROJECT_PATH/rootfs

OVERLAY_PATH=$WOLFBEAR_OS_PROJECT_PATH/overlay
ROOTFS_PATH=$WOLFBEAR_OS_PROJECT_PATH/rootfs

SDL_VERSION=

BUILD_ARCH=arm64
BUILD_CROSS_COMPILE=aarch64-linux-gnu-

mkdir -p $DEPENDENCIES_PATH

rm -rf $TARGET_PATH
mkdir $TARGET_PATH

echo "==== Running Linux Scripts ===="
cd $BUILD_SCRIPTS_PATH
source ./linux-kernel

echo "==== Running Overaly to RootFS Scripts ===="
cd $BUILD_SCRIPTS_PATH
source ./linux-overlay-to-rootfs

echo "==== Running BusyBox Scripts ===="
cd $BUILD_SCRIPTS_PATH
source ./busy-box

echo "==== Running rootfs packaging ===="
cd $BUILD_SCRIPTS_PATH
source ./rootfs-package
