#!/bin/sh
set -eu
set -o pipefail 2>/dev/null || true

source $WOLFBEAR_INSTALLER_DIR/globals

echo "Initializing apk database in rootfs directory"
/sbin/apk --root "$WOLFBEAR_TARGET_DISK_ROOTFS_MNT_DIR" \
  --repositories-file /dev/null \
  --allow-untrusted \
  --repository "$APK_UNCOMPRESSED_DIR" \
  add --initdb --no-scripts

echo "Updating apk-tools in rootfs directory"
/sbin/apk \
  --root $WOLFBEAR_TARGET_DISK_ROOTFS_MNT_DIR \
  --repositories-file /dev/null \
  --allow-untrusted \
  --repository "$APK_UNCOMPRESSED_DIR" \
  update