#!/bin/sh

echo "[rootfs-system-partitions] Montar particiones en rootfs"

echo "- Creando directorios del sistema para montar particiones"
sleep 0.5

mkdir -p /mnt/sda-root
mount /dev/sda2 /mnt/sda-root

mkdir -p /mnt/sda-root/boot/efi
umount /dev/sda1 2>/dev/null
sck.vfat -a /dev/sda1
mount /dev/sda1 /mnt/sda-root/boot/efi

mkdir -p /mnt/sda-root/proc
mkdir -p /mnt/sda-root/sys
mkdir -p /mnt/sda-root/dev

echo "- Montando en el nuevo root (rootfs)"
sleep 0.5

# Montar /dev, /proc, /sys dentro del nuevo root
mount --rbind /proc /mnt/sda-root/proc
mount --rbind /dev /mnt/sda-root/dev
mount --rbind /sys /mnt/sda-root/sys

echo "[rootfs-system-partitions] Particiones montadas exitosamente"
