#!/bin/sh

echo "[rootfs-system-partitions] Montar particiones en rootfs"

echo "- Creando directorios del sistema para montar particiones"
sleep 0.5

mkdir -p /mnt/vda-root
mount /dev/vda2 /mnt/vda-root

mkdir -p /mnt/vda-root/boot/efi
umount /dev/vda1 2>/dev/null
sck.vfat -a /dev/vda1
mount /dev/vda1 /mnt/vda-root/boot/efi

mkdir -p /mnt/vda-root/proc
mkdir -p /mnt/vda-root/sys
mkdir -p /mnt/vda-root/dev

echo "- Montando en el nuevo root (rootfs)"
sleep 0.5

# Montar /dev, /proc, /sys dentro del nuevo root
mount --rbind /proc /mnt/vda-root/proc
mount --rbind /dev /mnt/vda-root/dev
mount --rbind /sys /mnt/vda-root/sys

echo "[rootfs-system-partitions] Particiones montadas exitosamente"
