#!/bin/sh

set -euo pipefail

source ./globals

echo "Cleaning up previous initramfs output directory..."

rm -rf "$INITRMAFS_OUTPUT_DIR"
mkdir -p "$INITRMAFS_OUTPUT_DIR"

echo "Initramfs output directory cleaned and recreated at: $INITRMAFS_OUTPUT_DIR"