#!/bin/sh

set -euo pipefail

source ./globals

echo "Cleaning up previous initramfs output directory..."

rm -rf "$INITRAMFS_OUTPUT_DIR"
rm -rf "$BUSYBOX_DEPENDENCY_DIR"

mkdir -p "$INITRAMFS_OUTPUT_DIR"
mkdir -p "$BUSYBOX_DEPENDENCY_DIR"

echo "Initramfs output directory cleaned and recreated at: $INITRAMFS_OUTPUT_DIR"