#!/bin/sh
set -euo pipefail

source ./globals

echo "Setting permissions for initramfs output apk paths"

doas chmod 644 $INITRMAFS_OUTPUT_DIR/var/lib/apk/db/installed
doas chmod 644 $INITRMAFS_OUTPUT_DIR/var/lib/apk/db/world
doas chmod 644 $INITRMAFS_OUTPUT_DIR/etc/apk/world

echo "Permissions set for initramfs output apk paths successfully"

