#!/bin/sh
set -euo pipefail

source ./globals

echo "Setting permissions for initramfs output apk paths"

mkdir -p \
  "$INITRMAFS_OUTPUT_DIR/lib/apk/db" \
  "$INITRMAFS_OUTPUT_DIR/etc/apk" \
  "$INITRMAFS_OUTPUT_DIR/var/cache/apk"

touch "$INITRMAFS_OUTPUT_DIR/lib/apk/db/installed"
touch "$INITRMAFS_OUTPUT_DIR/lib/apk/db/world"

chmod 644 "$INITRMAFS_OUTPUT_DIR/lib/apk/db/installed"
chmod 644 "$INITRMAFS_OUTPUT_DIR/etc/apk/world"

echo "Permissions set for initramfs output apk paths successfully"

