#!/bin/sh
set -euo pipefail

echo "Adding passwd and shadow files to initramfs output directory"

echo 'root:x:0:0:root:/root:/bin/sh' >> $INITRMAFS_OUTPUT_DIR/etc/passwd
echo 'root::14600:0:99999:7:::' >> $INITRMAFS_OUTPUT_DIR/etc/shadow

echo "Setting SUID bit on ping binary in initramfs output directory"
doas chmod u+s $INITRMAFS_OUTPUT_DIR/bin/ping

echo "Passwd and shadow files added to initramfs output directory successfully"
