#!/bin/sh
set -euo pipefail

source ./globals

echo "Initializeing apk database in initramfs installer directory"
/sbin/apk --root "$INITRAMFS_OUTPUT_DIR" \
  --repositories-file /dev/null \
  --allow-untrusted \
  --repository "$APK_DEPENDENCY_COMPILED_DIR" \
  add --initdb --no-scripts

echo "Updating apk-tools in initramfs installer directory from repository"
/sbin/apk \
  --root $INITRAMFS_OUTPUT_DIR \
  --repositories-file /dev/null \
  --allow-untrusted \
  --repository "$APK_DEPENDENCY_COMPILED_DIR" \
  update

echo "Installing basic packages into initramfs installer directory..."
/sbin/apk \
  --root $INITRAMFS_OUTPUT_DIR \
  --repositories-file /dev/null \
  --allow-untrusted \
  --repository "$APK_DEPENDENCY_COMPILED_DIR" \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    e2fsprogs \
    dosfstools \
    rsync \
    nano \
    libc-utils \
    zstd \
    file \
    zip \
    unzip

echo "Basic packages installed into initramfs installer directory successfully"
