#!/bin/sh

echo "[wolfbear-scripts] starting scripts workflow"

./000-mount-system-partitions
# ./001-mount-graphics-cards
# ./002-setup-network
./003-user-quick-fixes

echo "[wolfbear-scripts] finishing scripts workflow"
