#!/bin/sh

echo "Revisando que el directorio para kms eglfs exista"
ls -l /usr/lib/qt6/plugins/egldeviceintegrations/libqeglfs-kms-integration.so

echo "Exportando variables QT"
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_INTEGRATION=kms
export QT_PLUGIN_PATH=/usr/lib/qt6/plugins
export QT_QPA_EGLFS_KMS_DEVICE=/dev/dri/card0
export QT_QPA_GENERIC_PLUGINS=evdevtouch,evdevkeyboard
export QT_QPA_EVDEV_MOUSE_PARAMETERS="/dev/input/event2:scale=0.5"

echo "Mostrando tarjetas graficas disponibles"
ls /dev/dri/
ls -l /dev/dri/card0

echo "Revisando que pertenezca la libreria a algo que esté presente"
ldd /usr/lib/qt6/plugins/egldeviceintegrations/libqeglfs-kms-integration.so

echo "Revisando que la integración libgbm esté presente"
ls -l /usr/lib/libgbm.so*

echo "Asignando permisos"
chmod a+rw /dev/dri/card0 /dev/dri/renderD128

cd /apps/wolfbear-apps/LauncherApp.d/
QT_LOGGING_RULES="qt.qpa.*=true" ./LauncherApp --wolfbearmode
