#!/bin/sh
set -eu
set -o pipefail 2>/dev/null || true

source $WOLFBEAR_INSTALLER_DIR/globals

lsblk -d -o NAME,SIZE,MODEL | grep -E 'sd|vd|nvme'
read -rp "¿En qué unidad quieres instalar? (/dev/sdX o /dev/vdX): " INSTALLATION_DISK

DEV_DISK="/dev/$(basename "$INSTALLATION_DISK")"

echo "IMPORTANTE: Se eliminará todo el contenido en '$DEV_DISK'"
read -rp "¿Deseas continuar? (y/[n]): " CONF

if [ "$CONF" != 'y' ]; then 
  echo "El proceso de instalación no puede continuar sin formatear el disco"
  exit 1
fi

echo "Calculando directorios de particiones"

EFI_PARTITION="${DEV_DISK}1"
ROOTFS_PARTITION="${DEV_DISK}2"

echo "Generando tabla de particiones en el disco"

parted --script "$DEV_DISK" \
  mklabel gpt \
  mkpart ESP fat32 1MiB 100MiB \
  set 1 esp on \
  mkpart primary ext4 100MiB 100%

echo "Formateando y particionando la unidad"

mkfs.vfat -F 32 "$EFI_PARTITION"
fatlabel "$EFI_PARTITION" WB_EFI_SYS

mkfs.ext4 "$ROOTFS_PARTITION"
e2label "$ROOTFS_PARTITION" WB_ROOTFS

echo "Montando particiones"

mkdir -p $WOLFBEAR_TARGET_DISK_ROOTFS_MNT_DIR
mount "$ROOTFS_PARTITION" "$WOLFBEAR_TARGET_DISK_ROOTFS_MNT_DIR"

mkdir -p $BOOT_EFI_DIR
mount "$EFI_PARTITION" "$BOOT_EFI_DIR"

mkdir -p "$BOOT_EFI_EFI_BOOT_DIR"

cp "$WOLFBEAR_INSTALLER_RESOURCES_MNT_DIR/linux/wolfbear-kernel_$WOLFBEAR_SYS_ARCH" "$BOOT_DIR/Image"
cp "$WOLFBEAR_INSTALLER_RESOURCES_MNT_DIR/linux/initramfs.la.cpio.xz" "$BOOT_DIR/"

echo "Formato y montaje base finalizado"