#!/bin/sh
set -eu
set -o pipefail 2>/dev/null || true

source $WOLFBEAR_INSTALLER_DIR/globals

echo "Generando GRUB según arquitectura: $WOLFBEAR_SYS_ARCH"

if [ "$WOLFBEAR_SYS_ARCH" = "amd64" ]; then
  grub-mkimage -O x86_64-efi -o $BOOT_EFI_EFI_BOOT_DIR/bootx64.efi -p "/EFI/BOOT" part_gpt fat ext2 normal configfile linux cpio gfxterm all_video
  echo 'fs0:\boot\grub\bootx64.efi' > $BOOT_EFI_EFI_BOOT_DIR/startup.nsh
elif [ "$WOLFBEAR_SYS_ARCH" = "arm64" ]; then
  grub-mkimage -O arm64-efi -o $BOOT_EFI_EFI_BOOT_DIR/bootaa64.efi -p "/EFI/BOOT" part_gpt fat ext2 normal configfile linux cpio gfxterm all_video
  echo 'fs0:\boot\grub\bootaa64.efi' > $BOOT_EFI_EFI_BOOT_DIR/startup.nsh
else
  echo "Arquitectura no soportada para GRUB: $WOLFBEAR_SYS_ARCH"
  exit 1
fi

echo "Generando archivo '$BOOT_EFI_EFI_BOOT_DIR/grub.cfg'"

cat > $BOOT_EFI_EFI_BOOT_DIR/grub.cfg <<EOF
set timeout=3
set default=0

menuentry "WolfbearOS for $WOLFBEAR_SYS_ARCH (ROOTFS)" {
    linux (hd1,gpt2)/boot/Image console=tty0 fbcon=map:0 root=/dev/sda2 rw
    initrd (hd1,gpt2)/boot/initramfs.la.cpio.xz
}
EOF
