#!/bin/sh

echo "=== Iniciando WolfbearOS ==="

# Las particiones del sistema se montaron en el launch de initramfs

# Pero aquí si es necesario exportar las variables para drivers de video
export LIBGL_DRIVERS_PATH=/usr/lib/dri
export SDL_VIDEODRIVER=KMSDRM
export SDL_KMSDRM_DEVICE=/dev/dri/card0
export SDL_KMSDRM_RENDER_NODE=/dev/dri/renderD128

./launch/run

# Bucle para mantener consola activa
for port in tty1 ttyAMA0; do
  if [ -e "/dev/$port" ]; then
    echo "[ROOTFS] WolfbearOS getty en $port"
    /sbin/getty -L "$port" 115200 vt100 &
  fi
done

# Esperar indefinidamente (para evitar que PID 1 muera)
wait