#!/bin/sh

echo "Bienvenido a WolfbearOS ROOTFS (Sistema Instalado)"

# Bucle para mantener consola activa
for port in tty1 ttyAMA0; do
  if [ -e "/dev/$port" ]; then
    echo "[ROOTFS] WolfbearOS getty en $port"
    /sbin/getty -L "$port" 115200 vt100 &
  fi
done

# Esperar indefinidamente (para evitar que PID 1 muera)
wait