#!/bin/sh
set -euo pipefail
source /launch/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando configuración de internet"

# Detectar si hay dirección IPv4 en eth0 usando awk
if ip -4 addr show eth0 | awk '$1 == "inet" { found = 1 } END { exit !found }'; then
    debug_message $SCRIPT_NAME "La interfaz eth0 ya tiene una IP asignada, omitiendo dhcpcd"
else
    debug_message $SCRIPT_NAME "No se detectó IP en eth0, ejecutando dhcpcd"
    mkdir -p /run/dhcpcd

    if timeout 5 dhcpcd eth0; then
        debug_message $SCRIPT_NAME "Conexión a internet realizada con éxito"
    else
        log_message $SCRIPT_NAME "dhcpcd falló o no respondió a tiempo"
    fi
fi

log_message $SCRIPT_NAME "Configuración de conexión a internet terminada"
