#!/bin/sh
set -euo pipefail
source /launch/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando configuración de internet"

debug_message $SCRIPT_NAME "Creando archivo de configuración DHCP"
mkdir -p /run/dhcpcd

debug_message $SCRIPT_NAME "Solicitando conexión a través de eth0"
new_line

dhcpcd eth0

debug_message $SCRIPT_NAME "Conexión a internet realizada con éxito"

log_message $SCRIPT_NAME "Configuración de conexión a internet terminada"