#!/bin/sh
set -euo pipefail
source /launch/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Solicitando la inicialización del launcher"

cd /apps/wolfbear-apps/LauncherApp.d/

QT_QPA_PLATFORM=kmsdrm \
QT_QPA_GENERIC_PLUGINS=evdevmouse,evdevkeyboard \
QT_QPA_EVDEV_MOUSE_PARAMETERS=/dev/input/event1:scale=0.3 \
./LauncherApp

log_message $SCRIPT_NAME "Launcher inicializado"