#!/bin/sh

SYS_ARCH=$(uname -m)
if [ "$SYS_ARCH" = 'aarch64' ] || [ "$SYS_ARCH" = 'arm64']; then
    SYS_ARCH="arm64"
else
    SYS_ARCH="amd64"
fi

log_message $SCRIPT_NAME "Iniciando configuración de internet DHCP" 5

debug_message $SCRIPT_NAME "Creando archivo de configuración DHCP"
mkdir -p /run/dhcpcd

debug_message $SCRIPT_NAME "Solicitando conexión a través de eth0"
new_line

dhcpcd eth0

debug_message $SCRIPT_NAME "Conexión a internet realizada con éxito"

log_message $SCRIPT_NAME "Configuración de conexión a internet terminada"

# echo $SYS_ARCH