#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando script para montar particiones del sistema"

debug_message $SCRIPT_NAME "Creando directorio de la unidad de instalación"
mkdir -p /mnt/install/

# Las particiones del sistema dev sys y proc ya las estamos montando en el init de initramfs
# por lo que no es necesario volverlas a montar aqui, solo los recursos de instalación

debug_message $SCRIPT_NAME "Montando recursos de instalación."
mount -t ext4 /dev/vda3 /mnt/install/

debug_message $SCRIPT_NAME "Particiones montadas exitosamente"

log_message $SCRIPT_NAME "Iniciando script para montar particiones del sistema"