#!/bin/bash
set -euo pipefail

echo "[initramfs-system-partitions] Montando particiones del sistema y dispositivos de instalación"

mkdir -p /mnt/install/

# Las particiones del sistema dev sys y proc ya las estamos montando en el init de initramfs
# por lo que no es necesario volverlas a montar aqui, solo los recursos de instalación

echo "- Montando recursos de instalación"
mount -t ext4 /dev/vda3 /mnt/install/

echo "[initramfs-system-partitions] Particiones montadas exitosamente"