#!/bin/sh
set -euo pipefail

echo "[network-setup] Iniciando configuración de internet"

echo "Creando archivo de configuración DHCP"
mkdir -p /run/dhcpcd

echo "Solicitando conexión a través de eth0"
dhcpcd eth0

echo "[setup-network] Conexión a internet realizada con éxito"
