#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando formateo e instalación de sistema base en disco"

debug_message $SCRIPT_NAME "Selecciona el dispositivo en el cual deseas instalar WolfbearOS:"
new_line

lsblk -d -o NAME,SIZE,MODEL | grep -E 'sd|vd|nvme'

read -rp "¿En qué unidad quieres instalar? (/dev/sdX o /dev/vdX): " INSTALLATION_DISK

DEV_DISK="/dev/$(basename "$INSTALLATION_DISK")"

debug_message $SCRIPT_NAME ""
echo "IMPORTANTE: Recuerda que se eliminará todo el contenido en en $DEV_DISK"

debug_message $SCRIPT_NAME ""
read -rp "¿Deseas continuar? (y/[n]): " CONF

if [ "$CONF" != 'y' ]; then 
  error_message $SCRIPT_NAME "El proceso de instalación no puede continuar. Reiniciando el sistema"
  reboot
fi

debug_message $SCRIPT_NAME "Calculando directorios de particiones"

EFI_PARTITION="${DEV_DISK}1"
ROOTFS_PARTITION="${DEV_DISK}2"

debug_message $SCRIPT_NAME "Generando tabla de particiones en el disco"

parted --script "$DEV_DISK" \
  mklabel gpt \
  mkpart ESP fat32 1MiB 100MiB \
  set 1 esp on \
  mkpart primary ext4 100MiB 100%

debug_message $SCRIPT_NAME "Formateando la unidad y sus particiones"

mkfs.vfat -F 32 "$EFI_PARTITION"
mkfs.ext4 "$ROOTFS_PARTITION"

debug_message $SCRIPT_NAME "Montando particiones"

BOOT_DIR="$TARGET_DISK_DIR/boot"
EFI_TARGET_DISK_DIR="$TARGET_DISK_DIR/boot/efi"
EFI_BOOT_TARGET_DISK_DIR="$TARGET_DISK_DIR/boot/efi/EFI/BOOT"

mkdir -p $TARGET_DISK_DIR
mount "$ROOTFS_PARTITION" "$TARGET_DISK_DIR"

mkdir -p $EFI_TARGET_DISK_DIR
mount "$EFI_PARTITION" "$EFI_TARGET_DISK_DIR"
mkdir -p "$EFI_BOOT_TARGET_DISK_DIR"

debug_message $SCRIPT_NAME "Generando imagen de GRUB"

grub-mkimage \
  -O arm64-efi \
  -p "/EFI/BOOT" \
  -o $EFI_BOOT_TARGET_DISK_DIR/BOOTAA64.EFI \
    part_gpt fat ext2 normal configfile linux cpio gfxterm all_video

debug_message $SCRIPT_NAME "Generando archivo $EFI_BOOT_TARGET_DISK_DIR/grub.cfg"

cat > $EFI_BOOT_TARGET_DISK_DIR/grub.cfg <<EOF
set timeout=0
set default=0

menuentry "WolfbearOS for ARM64 (rootfs)" {
    linux (hd0,gpt2)/boot/Image console=ttyAMA0 root=/dev/vda2 rw
    initrd (hd0,gpt2)/boot/initramfs.cpio.xz
}
EOF

debug_message $SCRIPT_NAME "Generando archivo $EFI_BOOT_TARGET_DISK_DIR/startup.nsh"

cat > $EFI_BOOT_TARGET_DISK_DIR/startup.nsh <<EOF
fs0:\EFI\BOOT\BOOTAA64.EFI
EOF

debug_message $SCRIPT_NAME "Cargando contenido de kernel para rootfs"

cp /mnt/install/linux-kernel/Image "$BOOT_DIR/"
cp /mnt/install/linux-kernel/initramfs.cpio.xz "$BOOT_DIR/"

log_message $SCRIPT_NAME "Instalación del sistema base en disco finalizada"