#!/bin/sh
set -euo pipefail

echo "[install-into-disk] Iniciando instalación en disco"
sleep 0.5

echo "Selecciona el dispositivo en el cual deseas instalar WolfbearOS:"
lsblk -d -o NAME,SIZE,MODEL | grep -E 'sd|vd|nvme'
read -rp "¿En qué disco quieres instalar? (/dev/sdX o /dev/vdX): " INSTALLATION_DISK
DEV_DISK="/dev/$(basename "$INSTALLATION_DISK")"

echo "¡¡¡ATENCIÓN!!! Recuerda que se eliminará todo en $DEV_DISK"
read -rp "¿Estás seguro? (y/[n]): " CONF
if [ "$CONF" != 'y' ]; then 
  echo "El proceso de instalación no puede continuar. Reiniciando el sistema"
  reboot
fi

echo "Planeando particiones"
sleep 0.5
EFI_PARTITION="${DEV_DISK}1"
ROOTFS_PARTITION="${DEV_DISK}2"

echo "Generando tabla de particiones en el disco"
sleep 0.5

parted --script "$DEV_DISK" \
  mklabel gpt \
  mkpart ESP fat32 1MiB 100MiB \
  set 1 esp on \
  mkpart primary ext4 100MiB 100%

echo "Formateando la unidad y sus particiones"
sleep 0.5

mkfs.vfat -F 32 "$EFI_PARTITION"
mkfs.ext4 "$ROOTFS_PARTITION"

echo "Montando particiones"
sleep 0.5

BOOT_DIR="$TARGET_DISK_DIR/boot"
EFI_TARGET_DISK_DIR="$TARGET_DISK_DIR/boot/efi"
EFI_BOOT_TARGET_DISK_DIR="$TARGET_DISK_DIR/boot/efi/EFI/BOOT"

mkdir -p $TARGET_DISK_DIR
mount "$ROOTFS_PARTITION" "$TARGET_DISK_DIR"

mkdir -p $EFI_TARGET_DISK_DIR
mount "$EFI_PARTITION" "$EFI_TARGET_DISK_DIR"
mkdir -p "$EFI_BOOT_TARGET_DISK_DIR"

echo "Generando imagen de GRUB"
sleep 0.5

grub-mkimage \
  -O arm64-efi \
  -p "/EFI/BOOT" \
  -o $EFI_BOOT_TARGET_DISK_DIR/BOOTAA64.EFI \
    part_gpt fat ext2 normal configfile linux cpio gfxterm all_video

echo "Generando archivo $EFI_BOOT_TARGET_DISK_DIR/grub.cfg"
sleep 0.5

cat > $EFI_BOOT_TARGET_DISK_DIR/grub.cfg <<EOF
set timeout=0
set default=0

menuentry "WolfbearOS for ARM64 (rootfs)" {
    linux (hd0,gpt2)/boot/Image console=ttyAMA0 root=/dev/vda2 rw
    initrd (hd0,gpt2)/boot/initramfs.cpio.xz
}
EOF

echo "Generando archivo $EFI_BOOT_TARGET_DISK_DIR/startup.nsh"
sleep 0.5

cat > $EFI_BOOT_TARGET_DISK_DIR/startup.nsh <<EOF
fs0:\EFI\BOOT\BOOTAA64.EFI
EOF

echo "Cargando contenido de kernel para rootfs"
sleep 0.5

cp /boot/Image "$BOOT_DIR/"
cp /boot/initramfs.cpio.xz "$BOOT_DIR/"

echo "[install-into-disk] Instalación en disco finalizada"
sleep 0.5
