#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Sincronizando capa de overlay/rootfs a '$TARGET_DISK_DIR'"

rsync -a --links "/mnt/install/rootfs-overlay/" "$TARGET_DISK_DIR/"

log_message $SCRIPT_NAME "Los cambios han sido sincronizados hacia '$TARGET_DISK_DIR'"