#!/bin/sh
set -euo pipefail

echo "[busybox-sync] Sincronizando directorios desde /mnt/install/modules-modprobe a raiz '$TARGET_DISK_DIR"
sleep 0.5

rsync -a --links "/mnt/install/modules-modprobe/" "$TARGET_DISK_DIR/"

echo "[busybox-sync] Sincronización terminada '$TARGET_DISK_DIR"
sleep 0.5