#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Sincronizado de cambios Busybox'$TARGET_DISK_DIR'"

rsync -a --links "/mnt/install/busybox-compiled/" "$TARGET_DISK_DIR/"

log_message $SCRIPT_NAME "Sincronización de cambios Busybox terminada '$TARGET_DISK_DIR'"