#!/bin/bash
set -euo pipefail

echo "[rootfs-system-partitions] Montando particiones del sistema y dispositivos en el sistema operativo final"

mount -t proc proc $TARGET_DISK_DIR/proc
mount --rbind /sys $TARGET_DISK_DIR/sys
mount --rbind /dev $TARGET_DISK_DIR/dev

echo "[rootfs-system-partitions] Particiones montadas exitosamente"