#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Preparando montaje de particiones del sistema hacia rootfs"

debug_message $SCRIPT_NAME "Creando directorios para particiones en '$TARGET_DISK_DIR'"
mkdir -p $TARGET_DISK_DIR/proc $TARGET_DISK_DIR/sys $TARGET_DISK_DIR/dev

debug_message $SCRIPT_NAME "Montando particiones del sistema en directorios creados"
mount -t proc proc $TARGET_DISK_DIR/proc
mount --rbind /sys $TARGET_DISK_DIR/sys
mount --rbind /dev $TARGET_DISK_DIR/dev

log_message $SCRIPT_NAME "Particiones montadas exitosamente"