#!/bin/sh
set -euo pipefail

echo "[install-dependencies] Instalando dependencias APK"
sleep 0.5

cp /etc/resolv.conf /mnt/target/etc/
cp /etc/apk/repositories /mnt/target/apk

/sbin/apk  update --root="$TARGET_DISK_DIR" \
  --cache-dir="$TARGET_DISK_DIR"/var/cache/apk

/sbin/apk --root="$TARGET_DISK_DIR" \
  --keys-dir /etc/apk/keys \
  --repositories-file /etc/apk/repositories \
  --cache-dir="$TARGET_DISK_DIR"/var/cache/apk \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    sdl2-dev sdl2 \
    libdrm \
    libdrm-dev \
    mesa-gbm \
    mesa-dev \
    linux-headers \
    mesa-dri-gallium \
    libinput-dev \
    expat-dev libffi-dev

echo "[install-dependencies] Instalación de dependencias APK terminada"
sleep 0.5