#!/bin/sh
set -euo pipefail

echo "[install-dependencies] Instalando dependencias APK"
sleep 0.5

mkdir -p "$TARGET_DISK_DIR"/etc/apk
cp /etc/apk/repositories "$TARGET_DISK_DIR"/etc/apk/
cp /etc/resolv.conf "$TARGET_DISK_DIR"/etc/

# 3) Crear manualmente las carpetas necesarias de APK
mkdir -p "$TARGET_DISK_DIR"/var/lib/apk/db
mkdir -p "$TARGET_DISK_DIR"/var/cache/apk

chmod 755 -R "$TARGET_DISK_DIR"/etc/apk
chmod 755 -R "$TARGET_DISK_DIR"/var/lib/apk/db
chmod 755 -R "$TARGET_DISK_DIR"/var/cache/apk

chmod 644 -R "$TARGET_DISK_DIR"/etc/resolv.conf

apk update --root=$TARGET_DISK_DIR \
  --cache-dir=$TARGET_DISK_DIR/var/cache/apk

apk --root=$TARGET_DISK_DIR \
  --keys-dir /etc/apk/keys \
  --repositories-file /etc/apk/repositories \
  --cache-dir=$TARGET_DISK_DIR/var/cache/apk \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    sdl2-dev sdl2 \
    libdrm \
    libdrm-dev \
    mesa-gbm \
    mesa-dev \
    linux-headers \
    mesa-dri-gallium \
    libinput-dev \
    expat-dev libffi-dev

echo "[install-dependencies] Instalación de dependencias APK terminada"
sleep 0.5