#!/bin/sh
set -euo pipefail
source /install/util-log
SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando instalación de dependencias apkt-tools"

debug_message $SCRIPT_NAME "Copiando archivo resolv.conf y asignando sus permisos"

cp /etc/resolv.conf "$TARGET_DISK_DIR"/etc/
chmod 644 "$TARGET_DISK_DIR"/etc/resolv.conf

debug_message $SCRIPT_NAME "Creando base de datos y world de apk-tools"
mkdir -p $TARGET_DISK_DIR/var/lib/apk/db
touch    $TARGET_DISK_DIR/var/lib/apk/db/installed
chmod 644 $TARGET_DISK_DIR/var/lib/apk/db/installed

mkdir -p $TARGET_DISK_DIR/etc/apk
touch    $TARGET_DISK_DIR/etc/apk/world
chmod 644 $TARGET_DISK_DIR/etc/apk/world

debug_message $SCRIPT_NAME "Sincronizando llaves de apk-tools"

mkdir -p $TARGET_DISK_DIR/etc/apk/keys
cp /etc/apk/keys/* $TARGET_DISK_DIR/etc/apk/keys

debug_message $SCRIPT_NAME "Actualizando base de datos de apk-tools"
new_line
apk update --root $TARGET_DISK_DIR

debug_message $SCRIPT_NAME "Descargando e instalando paquetes del sistema"
new_line
apk add --root $TARGET_DISK_DIR \
  apk-tools \
  shadow \
  dhcpcd \
  openresolv \
  util-linux \
  strace \
  openssh \
  grub-efi \
  parted \
  sdl2-dev sdl2 \
  libdrm \
  libdrm-dev \
  mesa-gbm \
  mesa-dev \
  linux-headers \
  mesa-dri-gallium \
  libinput libinput-dev \
  expat-dev libffi-dev \
  kmod \
  e2fsprogs \
  dosfstools \
  nano \
  git \
  libc-utils \
  file \
  libxkbcommon mesa-egl

# Instala compatibilidad con vulkan 
# apk add --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main --root $TARGET_DISK_DIR \
#  libxshmfence \
#  vulkan-loader \
#  vulkan-tools

log_message $SCRIPT_NAME "Instalación de dependencias APK terminada"