#!/bin/sh
set -euo pipefail

echo "[after-install-fixes] Ajustando recursos post instalación"
sleep 0.5

echo "- Solucionando problemas de ejecución del comando ping"
chmod u+s $TARGET_DISK_DIR/bin/ping

INSTALLED_FLAG="$TARGET_DISK_DIR/.wolfbearOSInstalled"
echo "- Marcando WolfbearOS como instalado '$INSTALLED_FLAG'"

chroot $TARGET_DISK_DIR /bin/sh -c "touch .wolfbearOSInstalled"

echo "[after-install-fixes] Recursos ajustados exitosamente"