#!/bin/sh
set -euo pipefail

echo "Definiendo variables de directorios"

export SYS_ARCH=$(uname -m)
if [ "$SYS_ARCH" = 'aarch64' ] || [ "$SYS_ARCH" = 'arm64' ]; then
	SYS_ARCH='arm64'
else 
	SYS_ARCH='amd64'
fi

export TARGET_DISK_DIR="/mnt/target"
export QT_VERSION=6.8.3
export INSTALL_RESOURCES_DIR="/mnt/install"