#!/bin/sh
set -euo pipefail
source /install/util-log
RUN_SCRIPT_NAME=$0

export TARGET_DISK_DIR="/mnt/target"
export CURRENT_PATH=$( pwd )
export SCRIPTS_DIR="$( dirname "$0" )/install"

log_message $RUN_SCRIPT_NAME "Bienvenido a instalación de WolfbearOS Developer\n"

export SYS_ARCH=$( ./000-arch-detection )

# Obtén la ruta real del script "install"
BASEDIR=$(cd "$(dirname "$0")" && pwd)

# Los scripts numerados están en el mismo directorio que este script
SCRIPTS_DIR="$BASEDIR"

if [ -z "${1-}" ]; then
  log_message $RUN_SCRIPT_NAME "Se ejecutarán todos los scripts en el directorio ./install/" 2
else
  SCRIPT_NAME_TO_EXECUTE=$1
  echo "Has solicitado ejecutar el script '$SCRIPT_NAME_TO_EXECUTE'."
  sh "$SCRIPT_NAME_TO_EXECUTE"
  exit 0
fi

i=0
while :; do
  prefix=$(printf "%03d" "$i")

  # Expande el patrón (efectúa globbing)
  set -- "$SCRIPTS_DIR/${prefix}-"*
  
  # Si no existe ningún fichero coincidente, $1 será literal y -e fallará
  if [ ! -e "$1" ]; then
    echo
    log_message $RUN_SCRIPT_NAME "Todos el flujo de trabajo se ha ejecutado"
    break
  fi

  # Ejecuta cada script existente y ejecutable usando sh
  for script in "$SCRIPTS_DIR/${prefix}-"*; do
    [ -f "$script" ] || continue
    if [ ! -x "$script" ]; then
      warn_message $RUN_SCRIPT_NAME "Saltando script $script (no es ejecutable)"
      continue
    fi
    log_message $RUN_SCRIPT_NAME "Corriendo script $script"
    sh "$script"
  done

  i=$((i + 1))
done

log_message $RUN_SCRIPT_NAME "El script de instalación de WolfbearOS ha finalizado exitosamente"