#!/bin/bash
set -euo pipefail

log_message(){
    script_name=$1
    sleep_time=$2
    message=$3

    echo "\033[0;34m[ $script_name ]\033[0;34m \033[0;32m[ LOG ]\033[0;32m \033[0m - $message"
    if [ -z "$sleepTime" ]; then
        sleep $sleep_time
    fi
} 

debug_message(){
    script_name=$1
    sleep_time=$2
    message=$3

    echo "\033[0;34m[ $script_name ]\033[0;34m \033[0;35m[ DEBUG ]\033[0;35m \033[0m - $message"
    if [ -z "$sleepTime" ]; then
        sleep $sleep_time
    fi
}

error_message(){
    script_name=$1
    sleep_time=$2
    message=$3

    echo "\033[0;34m[ $script_name ]\033[0;34m \033[0;31m[ ERROR ]\033[0;31m \033[0m - $message"
    if [ -z "$sleepTime" ]; then
        sleep $sleep_time
    fi
} 

warn_message(){
    script_name=$1
    sleep_time=$2
    message=$3

    echo "\033[0;34m[ $script_name ]\033[0;34m \033[0;33m[ WARN ]\033[0;33m \033[0m - $message"
    if [ -z "$sleepTime" ]; then
        sleep $sleep_time
    fi
}