#! /bin/sh
set -euo pipefail

source ./globals

echo "Downloading linux kernel from wolfbear-os repository"

if [ "$SYS_ARCH" == "amd64" ]; then
  REMOTE_IMAGE_NAME="bzImage";
elif [ "$SYS_ARCH" == "arm64" ]; then
  REMOTE_IMAGE_NAME="Image";
else
  echo "Unsupported architecture: $SYS_ARCH"
  exit 1
fi

rm -rf $ROOT_DIR/sources
mkdir -p $ROOT_DIR/sources

mkdir -p $( dirname $LINUX_KERNEL_DEPENDENCY_COMPILED_FILENAME_DIR )
mkdir -p $( dirname $APK_DEPENDENCY_COMPRESSED_FILENAME_DIR )

mkdir -p "$BUSYBOX_DEPENDENCY_DIR"
mkdir -p "$APK_DEPENDENCY_COMPILED_DIR"
# mkdir -p "$QT_EVERYWHERE_DEPENDENCY_COMPRESSED_DIR"

mkdir -p "$WOLFBEAR_APPS_SOURCE_DIR"

# Checking for cache for Linux Kernel
echo "[ WolfbearOs ] [ info ] importing Linux kernel"
if [[ -f "$LINUX_DEPENDENCY_CACHE_DIR/$REMOTE_IMAGE_NAME" ]]; then
  echo "[ WolfbearOs ] [ cache ] copying from '$LINUX_DEPENDENCY_CACHE_DIR/$REMOTE_IMAGE_NAME'"
  cp "$LINUX_DEPENDENCY_CACHE_DIR/$REMOTE_IMAGE_NAME" "$LINUX_KERNEL_DEPENDENCY_COMPILED_FILENAME_DIR"
  else 
  echo "[ WolfbearOs ] [ repo ] downloading from 'http://os.wolfbear.mx/wolfbear-os_1.0/linux/$SYS_ARCH/6.17/$REMOTE_IMAGE_NAME'"
  wget -O "$LINUX_KERNEL_DEPENDENCY_COMPILED_FILENAME_DIR" \
    "http://os.wolfbear.mx/wolfbear-os_1.0/linux/$SYS_ARCH/6.17/$REMOTE_IMAGE_NAME"
fi

# Checking for cache for Busybox
echo "[ WolfbearOs ] [ info ] importing Busybox"
if [[ -f "$BUSYBOX_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" ]]; then
  echo "[ WolfbearOs ] [ cache ] copying from '$BUSYBOX_DEPENDENCY_CACHE_ZIP_FILENAME_DIR"
  cp "$BUSYBOX_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" "$BUSYBOX_DEPENDENCY_DIR/busybox.zip"
else 
  echo "[ WolfbearOs ] [ repo ] downloading from 'http://os.wolfbear.mx/wolfbear-os_1.0/busybox/$SYS_ARCH/1.37.0/busybox.zip'"
  wget -O "$BUSYBOX_DEPENDENCY_DIR" \
    "http://os.wolfbear.mx/wolfbear-os_1.0/busybox/$SYS_ARCH/1.37.0/busybox.zip"
fi

# Checking for cache for APKs

echo "[ WolfbearOs ] [ info ] importing APKs"
if [[ -f "$APK_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" ]]; then
  echo "[ WolfbearOs ] [ cache ] copying from '$APK_DEPENDENCY_CACHE_ZIP_FILENAME_DIR'"
  cp "$APK_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" "$APK_DEPENDENCY_COMPRESSED_FILENAME_DIR"
else 
  echo "[ WolfbearOs ] [ repo ] downloading from 'http://os.wolfbear.mx/wolfbear-os_1.0/apk_$SYS_ARCH.zip'"
  wget -O "$APK_DEPENDENCY_COMPRESSED_FILENAME_DIR" \
    "http://os.wolfbear.mx/wolfbear-os_1.0/apk_$SYS_ARCH.zip"
fi
unzip "$APK_DEPENDENCY_COMPRESSED_FILENAME_DIR" -d "$APK_DEPENDENCY_COMPILED_DIR/../"


# echo "[ WolfbearOs ] [ info ] importing QT Everywhere (compiled)"
# if [[ -f "$QT_EVERYWHERE_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" ]]; then
#   echo "[ WolfbearOs ] [ cache ] copying from '$QT_EVERYWHERE_DEPENDENCY_CACHE_ZIP_FILENAME_DIR'"
#   cp "$QT_EVERYWHERE_DEPENDENCY_CACHE_ZIP_FILENAME_DIR" "$QT_EVERYWHERE_DEPENDENCY_COMPRESSED_FILENAME_DIR"
# else 
#   echo "[ WolfbearOs ] [ repo ] downloading from 'http://os.wolfbear.mx/wolfbear-os_1.0/qt-everywhere/$SYS_ARCH/$QT_VERSION/qt.tar.zst'"
#   wget -O "$QT_EVERYWHERE_DEPENDENCY_COMPRESSED_FILENAME_DIR" \
#     "http://os.wolfbear.mx/wolfbear-os_1.0/qt-everywhere/$SYS_ARCH/$QT_VERSION/qt.tar.zst"
# fi


echo "[ WolfbearOs ] [ info ] importing WolfbearApps (compiled)"
if [[ -f "$WOLFBEAR_APPS_CACHE_ZIP_FILENAME_DIR" ]]; then
  echo "[ WolfbearOs ] [ cache ] copying from '$WOLFBEAR_APPS_CACHE_ZIP_FILENAME_DIR'"
  cp "$WOLFBEAR_APPS_CACHE_ZIP_FILENAME_DIR" "$WOLFBEAR_APPS_SOURCE_ZIP_FILENAME_DIR"
else 
  echo "[ WolfbearOs ] [ repo ] downloading from 'http://os.wolfbear.mx/wolfbear-os_1.0/wbapps/$SYS_ARCH/wolfbear-apps.tar.gz'"
  wget -O "$WOLFBEAR_APPS_SOURCE_ZIP_FILENAME_DIR" \
    "http://os.wolfbear.mx/wolfbear-os_1.0/wbapps/$SYS_ARCH/wolfbear-apps.tar.gz"
fi

echo "Dependencies imported successfully."