#!/bin/sh

echo "[mount-graphics-cards] begin"

echo "- Creating /dev/dri"
mkdir -p /dev/dri

echo "- Mounting card0 and renderD128 drivers"
[ ! -e /dev/dri/card0 ] && mknod -m 0666 /dev/dri/card0 c 226 0
[ ! -e /dev/dri/renderD128 ] && mknod -m 0666 /dev/dri/renderD128 c 226 128

echo "- Assigning permissions to drivers card"
chmod 0666 /dev/dri/card0 /dev/dri/renderD128

echo "- Exporting SDL and LIBGL environment variables"
export LIBGL_DRIVERS_PATH=/usr/lib/dri
export SDL_VIDEODRIVER=KMSDRM
export SDL_KMSDRM_DEVICE=/dev/dri/card0
export SDL_KMSDRM_RENDER_NODE=/dev/dri/renderD128

echo "- Adding DRM and VIRTIO modules"
modprobe drm
modprobe virtio_gpu
modprobe drm_kms_helper

echo "[mount-graphics-cards] end"
