#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando limpieza de ./target"
debug_message $SCRIPT_NAME "Desmontando particiones montadas en '$TARGET_DIR'"

for fs in proc sys dev; do
  mountpoint -q "$TARGET_DIR/$fs" && sudo umount -l "$TARGET_DIR/$fs"
done

debug_message $SCRIPT_NAME "Eliminando directorio '$TARGET_DIR'"
sudo rm -rf "$TARGET_DIR"

debug_message $SCRIPT_NAME "Creando directorio vacío '$TARGET_DIR'"
mkdir -p "$TARGET_DIR"

log_message $SCRIPT_NAME "Limpieza de ./target finalizada"