#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando limpieza de '$LINUX_MODPROBE_MODULES_DIR'"

debug_message $SCRIPT_NAME "Eliminando directorio '$LINUX_MODPROBE_MODULES_DIR'"
sudo rm -rf "$LINUX_MODPROBE_MODULES_DIR"

debug_message $SCRIPT_NAME "Creando directorio vacío '$LINUX_MODPROBE_MODULES_DIR'"
mkdir -p "$LINUX_MODPROBE_MODULES_DIR"

log_message $SCRIPT_NAME "Limpieza de '$LINUX_MODPROBE_MODULES_DIR' finalizada"