#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando descarga del kernel de linux '$DEPENDENCY_LINUX_DIR'"

if [ ! -d "$DEPENDENCY_LINUX_DIR" ] || [ -z "$(ls -A "$DEPENDENCY_LINUX_DIR")" ]; then
	log_message $SCRIPT_NAME "La dependencia de Linux Kernel no se encontró en el sistema"
	log_message $SCRIPT_NAME "Linux Kernel será descargado desde su repositorio oficial"
	new_line

	git clone -b v$VERSION_LINUX_KERNEL --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $DEPENDENCY_LINUX_DIR

	log_message $SCRIPT_NAME "La dependencia de Linux Kernel se ha descargado exitosamente"
else 
	log_message $SCRIPT_NAME "No es necesario descargar Linux Kernel ya que fue encontrado en la carpeta de dependencias"
fi

log_message $SCRIPT_NAME "El script para descargar Linux Kernel ha finalizado"