#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Configuración base de datos apk-tools en '$INITRAMFS_DIR'"

debug_message $SCRIPT_NAME "Creando directorio de base de datos"
mkdir -p $INITRAMFS_DIR/var/lib/apk/db

debug_message $SCRIPT_NAME "Creando archivo installed en directorio de base de datos"
doas touch    $INITRAMFS_DIR/var/lib/apk/db/installed
doas chmod 644 $INITRAMFS_DIR/var/lib/apk/db/installed

debug_message $SCRIPT_NAME "Creando directorio en /etc de apk-tools"
mkdir -p $INITRAMFS_DIR/etc/apk

debug_message $SCRIPT_NAME "Creando archivo world en directorio /etc de apk-tools"
doas touch    $INITRAMFS_DIR/etc/apk/world
doas chmod 644 $INITRAMFS_DIR/etc/apk/world


debug_message $SCRIPT_NAME "Sincronizando llaves de repositorios desde host Alpine"
mkdir -p $INITRAMFS_DIR/etc/apk/keys
cp /etc/apk/keys/* $INITRAMFS_DIR/etc/apk/keys

debug_message $SCRIPT_NAME "Soliciatndo actualización de base de datos apk update"
doas /sbin/apk update --root $INITRAMFS_DIR

log_message $SCRIPT_NAME "Configuración de base de datos terminada"
