#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Instalar paquetes básicos '$INITRAMFS_DIR'"

doas /sbin/apk --root $INITRAMFS_DIR \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    e2fsprogs \
    dosfstools \
    rsync \
    nano

log_message $SCRIPT_NAME "Instalación de paquetes básicos terminada"
