#!/bin/sh
set -euo pipefail

echo "Definiendo variables de directorios"

export WOLFBEAR_OS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
export SCRIPTS_DIR="$WOLFBEAR_OS_DIR/new-scripts"

echo "WOLFBEAR_OS_DIR: $WOLFBEAR_OS_DIR"
