#!/bin/sh
set -euo pipefail

SCRIPT_NAME=$0

export CURRENT_PATH=$( pwd )
export SCRIPTS_DIR="$( dirname "$0" )"

doas echo "Compilación de WolfbearOS en initramfs ha empezado"

BASEDIR=$(cd "$(dirname "$0")" && pwd)

source "$BASEDIR/globals-definitions"

echo "$WOLFBEAR_OS_DIR en run"

if [ -z "${1-}" ]; then
  echo "Has solicitado ejecutar todos los scripts del directorio."
else
  SCRIPT_NAME_TO_EXECUTE=$1
  echo "Has solicitado ejecutar el script '$SCRIPT_NAME_TO_EXECUTE'."
  sh "$SCRIPT_NAME_TO_EXECUTE"
  exit 0
fi

i=0
while :; do
  prefix=$(printf "%03d" "$i")
  set -- "$SCRIPTS_DIR/${prefix}-"*

  if [ ! -e "$1" ]; then
    echo
    echo "Se ha terminado la ejecución de los scripts (ya no existe el script ${prefix}-*)"
    break
  fi

  for script in "$SCRIPTS_DIR/${prefix}-"*; do
    [ -f "$script" ] || continue
    if [ ! -x "$script" ]; then
      echo "Saltando script $script (no es ejecutable)"
      continue
    fi

    echo
    echo "Corriendo script $script"
    script_name="$(basename "$script")"

    if echo "$script_name" | grep -qE '^[0-9]{3}-doas-'; then
      echo "→ Este script requiere permisos de superusuario (doas)"

      doas env \
        SYS_ARCH="$SYS_ARCH" \
        VERSION_LINUX_KERNEL="$VERSION_LINUX_KERNEL" \
        BUSY_BOX_VERSION="$BUSY_BOX_VERSION" \
        WOLFBEAR_OS_DIR="$WOLFBEAR_OS_DIR" \
        SCRIPTS_DIR="$SCRIPTS_DIR" \
        TARGET_DIR="$TARGET_DIR" \
        PATCHES_DIR="$PATCHES_DIR" \
        CONFIG_FILES_DIR="$CONFIG_FILES_DIR" \
        INITRAMFS_DIR="$INITRAMFS_DIR" \
        DEPENDENCIES_DIR="$DEPENDENCIES_DIR" \
        DEPENDENCY_LINUX_DIR="$DEPENDENCY_LINUX_DIR" \
        DEPENDENCIES_LINUX_MODULES_DIR="$DEPENDENCIES_LINUX_MODULES_DIR" \
        DEPENDENCY_BUSYBOX_DIR="$DEPENDENCY_BUSYBOX_DIR" \
        DEPENDENCY_BUSYBOX_COMPILED_DIR="$DEPENDENCY_BUSYBOX_COMPILED_DIR" \
        DEPENDENCY_WOLFBEAR_APPS_DIR="$DEPENDENCY_WOLFBEAR_APPS_DIR" \
        OVERLAY_DIR="$OVERLAY_DIR" \
        OVERLAY_INITRAMFS_DIR="$OVERLAY_INITRAMFS_DIR" \
        OVERLAY_ROOTFS_DIR="$OVERLAY_ROOTFS_DIR" \
        OVERLAY_SYSAPPS_DIR="$OVERLAY_SYSAPPS_DIR" \
        sh "$script"
    else
      source "$script"
    fi
  done

  i=$((i + 1))
done

echo "Compilación de WolfbearOS ha terminado"
exit 0
