#!/bin/sh

echo "=== Runing WolfbearOS init scripts ==="

I_AM_INSTALLED=$( cat iminstalled )
if [ "$I_AM_INSTALLED" = 'y' ]; then
	exec /launch/scripts
fi

while true; do
	clear
	
	echo "WolfbearOS initramfs"

	/sbin/getty -L ttyAMA0 115200 vt1000

	echo "Woof bye!"
	sleep 2
done
