#!/bin/sh
set -euo pipefail

# Script init para initramfs de WolfbearOS
# Monta la partición, comprueba la instalación y lanza instalador si es necesario

echo "[initramfs] Arrancando sistemas virtuales..."
mkdir -p /proc /sys /dev
mount -t devtmpfs dev /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys

# Definir punto de montaje
defined_mnt="/mnt/sda-root"
mkdir -p "$defined_mnt"

DISK="/dev/sda2"
TIMEOUT=10

echo "Esperando que $DISK esté disponible..."

for i in $(seq 1 $TIMEOUT); do
  if [ -b "$DISK" ]; then
    echo "$DISK está listo."
    break
  fi
  echo "Intento $i: $DISK aún no está disponible. Esperando..."
  sleep 0.5
done

if [ ! -b "$DISK" ]; then
  echo "[ERROR] $DISK no apareció tras $TIMEOUT segundos. Abortando."
  exit 0.5
fi

sleep 0.5

# Intento de montaje
if mount "$DISK" /dev/sda2; then
    sleep 0.5
    # Si está instalado, lanzamos el sistema
    if [ -f "$defined_mnt/.wolfbearOSInstalled" ]; then
        echo "[initramfs] WolfbearOS detectado. Iniciando sistema.."
        sh /launch/run || echo "[initramfs] Error al iniciar el sistema."
    else
        # Partición OK pero sin instalación
        motivo="sin_instalar"
    fi
else
    # No se montó la partición
    motivo="sin_particion"
fi

# Si hay motivo, ejecutamos instalador
if [ -n "${motivo-}" ]; then
    caso="$motivo"
    [ "$caso" = "sin_particion" ] && msg="no se pudo montar la partición"
    [ "$caso" = "sin_instalar" ]  && msg="no existe una instalación de WolfbearOS"
    echo "[initramfs] Lanzando instalador: $msg."
    sh /install/run || echo "[initramfs] La instalación falló"
fi

# Bucle para mantener consola activa
for port in tty1 ttyAMA0; do
  if [ -e "/dev/$port" ]; then
    echo "[initramfs] WolfbearOS getty en $port"
    /sbin/getty -L "$port" 115200 vt100 &
  fi
done

# Esperar indefinidamente (para evitar que PID 1 muera)
wait