#!/bin/sh
set -euo pipefail

echo "[initramfs-dependencies-install] starting dependency install"
sleep 0.5

echo "- ./initramfs path: '$INITRAMFS_PATH'"
sleep 0.5

echo "- ./overlay path: '$OVERLAY_INITRAMFS_PATH'"
sleep 0.5

echo "- ./modprobe-compiled path: '$MODPROBE_COMPILED_DIR'"
sleep 0.5

echo "- Syncing overlay path to external path"
rsync -a --links "$OVERLAY_INITRAMFS_PATH/" "$INITRAMFS_PATH/"

echo "- Preparing ./initramfs directories"
sleep 0.5

mkdir -p \
  "$INITRAMFS_PATH/tmp" \
  "$INITRAMFS_PATH/sbin" \
  "$INITRAMFS_PATH/lib/apk/db" \
  "$INITRAMFS_PATH/etc/apk" \
  "$INITRAMFS_PATH/etc/ssl/certs" \
  "$INITRAMFS_PATH/usr/lib"

echo "- Creando base de datos y world de apk-tools"
sleep 0.5

mkdir -p $TARGET_DISK_DIR/var/lib/apk/db
touch    $TARGET_DISK_DIR/lib/apk/db/installed
chmod 644 $TARGET_DISK_DIR/lib/apk/db/installed

mkdir -p $TARGET_DISK_DIR/etc/apk
touch    $TARGET_DISK_DIR/apk/world
chmod 644 $TARGET_DISK_DIR/apk/world

echo "-Actualizando keys del equipo local hacia initramfs"
sleep 0.5

mkdir -p $TARGET_DISK_DIR/etc/apk/keys
cp /etc/apk/keys/* $INITRAMFS_PATH/etc/apk/keys

echo "- Actualizando base de datos"
doas /sbin/apk update --root $TARGET_DISK_DIR

echo "- Instalando dependencias"
sleep 0.5

doas /sbin/apk --root= $INITRAMFS_PATH \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    e2fsprogs \
    rsync \
    nano

echo "- Setting up root user"
sleep 0.5
echo 'root:x:0:0:root:/root:/bin/sh' >> $INITRAMFS_PATH/etc/passwd
echo 'root::14600:0:99999:7:::' >> $INITRAMFS_PATH/etc/shadow

echo "- Fixing ping command sudo execution"
sleep 0.5
sudo chmod u+s $INITRAMFS_PATH/bin/ping

echo "[initramfs-dependencies-install] build finished"
sleep 0.5
