#! /bin/sh

WOLFBEAR_OS_DIR=$( dirname $(pwd) )
WOLFBEAR_APPS_COMPILED_HOST="192.168.64.9"

OVERLAY_SYSAPPS_DIR="$WOLFBEAR_OS_DIR/overlay/sys-apps/apps"

echo "wolfbear-os dir: '$WOLFBEAR_OS_DIR'"
echo "compilation host: '$WOLFBEAR_APPS_COMPILED_HOST'"

scp $WOLFBEAR_APPS_COMPILED_HOST:~/wolfbear-utils/target/LauncherApp.zip $OVERLAY_SYSAPPS_DIR

rm -rf $OVERLAY_SYSAPPS_DIR/LauncherApp.d
mkdir -p $OVERLAY_SYSAPPS_DIR/LauncherApp.d

unzip $OVERLAY_SYSAPPS_DIR/LauncherApp.zip -d $OVERLAY_SYSAPPS_DIR/LauncherApp.d