#! /bin/sh

WOLFBEAR_OS_DIR=$( dirname $(pwd) )
WOLFBEAR_APPS_COMPILED_HOST="192.168.64.9"

echo "wolfbear-os dir: '$WOLFBEAR_OS_DIR'"
echo "compilation host: '$WOLFBEAR_APPS_COMPILED_HOST'"

scp $WOLFBEAR_APPS_COMPILED_HOST:~/wolfbear-utils/target/LauncherApp.zip $WOLFBEAR_OS_DIR