#! /bin/bash

echo "[STEP BEGIN] app-hello-world compilation start"

sleep 0.5
if [ "$1" = 'local' ]; then

	current_dir=$(pwd)

	WOLFBEAR_OS_PROJECT_PATH=$( echo ${current_dir%/*} )

	PKG_EXTERNAL_PATH=$WOLFBEAR_OS_PROJECT_PATH/pkg-external
	OVERLAY_PATH=$WOLFBEAR_OS_PROJECT_PATH/overlay
	WOLFBEAR_APPS_PATH=$OVERLAY_PATH/apps

fi

echo "  Configuring pkg config path"
sleep 0.5
PKG_CONFIG_PATH="${PKG_EXTERNAL_PATH}/usr/lib/pkgconfig"

echo "  Compiling application"
sleep 0.5

aarch64-linux-musl-gcc \
  -static \
  -o "${WOLFBEAR_APPS_PATH}/sdl_hello/sdl_hello.wbapp" \
  "${WOLFBEAR_APPS_PATH}/sdl_hello/sdl_hello.c" \
  --sysroot="$PKG_EXTERNAL_PATH" \
  -I"$PKG_EXTERNAL_PATH/usr/include" \
  -L"$PKG_EXTERNAL_PATH/usr/lib" \
  -lSDL2 \
  -lm

  echo "  Compilation finished"
sleep 0.5

echo "[STEP END] app-hello-world compilation success"
sleep 1
