#! /bin/sh

echo "[STEP BEGIN] app-hello-world compilation start"
sleep 1

echo "- Configuring pkg config path"
sleep 1

PKG_CONFIG_PATH="${PKG_EXTERNAL_PATH}/usr/lib/pkgconfig"

echo "- Compiling hello world application aarch64-linux-musl-gcc"
sleep 1

gcc \
  -o "${WOLFBEAR_APPS_PATH}/sdl_hello/sdl_hello.wbapp" \
  "${WOLFBEAR_APPS_PATH}/sdl_hello/sdl_hello.c" \
  --sysroot="$PKG_EXTERNAL_PATH" \
  -I"$PKG_EXTERNAL_PATH/usr/include" \
  -L"$PKG_EXTERNAL_PATH/usr/lib" \
  -Wl,-rpath=/usr/lib \
  -lSDL2 -lgbm -ldrm -lexpat -lffi -lm

echo "- Compilation finished"
sleep 1

echo "[STEP END] app-hello-world compilation success"
sleep 1
