#!/bin/bash

echo "== Building BusyBox"

cd $DEPENDENCIES_PATH

if [ ! -d $BUSY_BOX_PATH ]; then
	echo "-- BusyBox was not found, downloading it.."
	sleep 0.5

	wget https://busybox.net/downloads/busybox-$BUSY_BOX_VERSION.tar.bz2

	echo "Uncompressing BusyBox"
	sleep 0.5

	tar -xjf busybox-$BUSY_BOX_VERSION.tar.bz2

	echo "Moving BusyBox to it's dependency path"
	sleep 0.5

	mv busybox-$BUSY_BOX_VERSION busybox
else
	echo "-- BusyBox was found in dependencies path"
	sleep 0.5
fi

cd $BUSY_BOX_PATH

echo "-- Overwriting .config file from busybox-config"
sleep 0.5

rm -f .config
cp $CONFIG_FILES_PATH/busybox-config .config

# We do not apply busybox patches yet
# echo "-- Applying busybox patches"
# sleep 0.5
# patch -p1 < $PATCHES_PATH/kernel.patch

make ARCH=$BUILD_ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE oldconfig

echo "-- Compiling BusyBox"
sleep 0.5
make ARCH=$BUILD_ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE -j$(nproc)

echo "-- Installing BusyBox"
sleep 0.5
make ARCH=$BUILD_ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE CONFIG_PREFIX=$BUSY_BOX_CONFIG_PREFIX install

echo "== Busybox installed successfully"
