#!/bin/bash

echo "== Building Linux Kernel"

if [ ! -d $LINUX_KERNEL_PATH ]; then
	echo "-- Linux kernel was not found, downloading it.."
	sleep 0.5

	git clone -b v$LINUX_KERNEL_VERSION --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git $LINUX_KERNEL_PATH
fi

cd $LINUX_KERNEL_PATH

echo "-- Linux kernel is ready to be compiled"
sleep 0.5

echo "-- Overwriting .config file from linux-config"
sleep 0.5
rm -f .config
cp $CONFIG_FILES_PATH/linux-config .config

echo "-- Checking kernel patches"
sleep 0.5
if patch --dry-run --forward -p1 < $PATCHEs_PATH/kernel.patch > /dev/null; then
	echo "Applying kernel patches"
	patch -p1 < $PATCHES_PATH/kernel.patch
else
	echo "No kernel patch needed"
fi

make ARCH=$BUILD_ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE oldconfig

echo "-- Compiling wolfbearOS Linux kernel"
sleep 0.5
make ARCH=$BUILD_ARCH CROSS_COMPILE=$BUILD_CROSS_COMPILE -j$(nproc)

echo "-- Moving compiled Image to compilation path"
sleep 0.5
mv $LINUX_KERNEL_PATH/arch/arm64/boot/Image $TARGET_PATH
