#!/bin/bash

echo "  Package external build script"
sleep 1

echo "  Downloading Alpine APK Tools"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/etc/apk
echo "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main" > $PKG_EXTERNAL_PATH/etc/apk/repositories

echo " Initializating APK Tools Database"
apk --root $PKG_EXTERNAL_PATH --initdb
