#!/bin/bash

echo "[STEP BEGIN] pkg-external-dependencies-alpine-docker"
sleep 1

echo "  Verifying required paths exist"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/usr/include $PKG_EXTERNAL_PATH/usr/lib


echo "  Running Docker Image"
sleep 1
docker run --rm -v $PKG_EXTERNAL_PATH:/target alpine:3.18 \
  /bin/sh -c "\
    apk update && \
    apk add --no-cache sdl2-dev && \
    cp -a /usr/include/SDL2 /target/usr/include/ && \
    cp -a /usr/lib/libSDL2* /target/usr/lib/"


echo "  Checking dependencies were installed successfully"
sleep 1
ls $PKG_EXTERNAL_PATH/usr/include/SDL2
ls $PKG_EXTERNAL_PATH/usr/lib | grep libSDL2

echo "[STEP END] pkg-external-dependencies-alpine-docker"
sleep 1
