#!/bin/bash

echo "[STEP] Package external APK tools setup in ./pkg-external"
sleep 1

echo "  Verifying apk-tools required paths"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH

echo "  Creating configuration paths"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/etc/apk/keys

echo "  Creating package database"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/lib/apk/db
touch $PKG_EXTERNAL_PATH/lib/apk/db/installed

echo "  Creating log path"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/var/log
touch $PKG_EXTERNAL_PATH/var/log/apk.log

echo " Setting up package installation prefixes"
sleep 1
mkdir -p $PKG_EXTERNAL_PATH/usr/{bin,lib,include,sbin}




echo "  Create index cache"
sleep 1
mkdir -p \
  $PKG_EXTERNAL_PATH/etc/apk \
  $PKG_EXTERNAL_PATH/var/cache/apk \
  $PKG_EXTERNAL_PATH/sdl2-packages

echo "  Configuring repositories"
sleep 1
cat > $PKG_EXTERNAL_PATH/etc/apk/repositories <<EOF
https://dl-cdn.alpinelinux.org/alpine/v3.18/main
https://dl-cdn.alpinelinux.org/alpine/v3.18/community
EOF

echo "  Descargando APKINDEX (índices de paquetes)..."
sleep 1
wget -q -O $PKG_EXTERNAL_PATH/var/cache/apk/APKINDEX.tar.gz \
  https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz

wget -q -O $PKG_EXTERNAL_PATH/var/cache/apk/community-APKINDEX.tar.gz \
  https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz




echo "  Adjusting permissions"
# config de apk
chmod 755 $PKG_EXTERNAL_PATH/etc $PKG_EXTERNAL_PATH/etc/apk
chmod 700 $PKG_EXTERNAL_PATH/etc/apk/keys

# repositorios
chmod 644 $PKG_EXTERNAL_PATH/etc/apk/repositories

# db de apk
chmod 755 $PKG_EXTERNAL_PATH/lib $PKG_EXTERNAL_PATH/lib/apk $PKG_EXTERNAL_PATH/lib/apk/db
chmod 644 $PKG_EXTERNAL_PATH/lib/apk/db/installed

# log
chmod 755 $PKG_EXTERNAL_PATH/var $PKG_EXTERNAL_PATH/var/log
chmod 644 $PKG_EXTERNAL_PATH/var/log/apk.log

# prefijo de instalación (rw para tu usuario, x para entrar)
chmod -R u+rwX $PKG_EXTERNAL_PATH/usr
chmod -R u+rwX $PKG_EXTERNAL_PATH

echo "[STEP] Package external has initialized ./pkg-external path"
sleep 1
