#!/bin/sh
set -euo pipefail
source ./util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Iniciando script de cleanup"
sleep 0.5

echo "- ./initramfs path: '$INITRAMFS_PATH'"
sleep 0.5

echo "- ./target path: '$TARGET_PATH'"
sleep 0.5

echo "- Is it requested to clean modules kernel cache?: $VAR_KERNEL_MODULES_COMPILE"
sleep 0.5

echo "- Umounting lazy partitions"
sleep 0.5

for fs in proc sys dev; do
  mountpoint -q "$INITRAMFS_PATH/$fs" && sudo umount -l "$INITRAMFS_PATH/$fs"
done

echo "- Cleaning ./initramfs path"
sleep 0.5

sudo rm -rf "$INITRAMFS_PATH"
mkdir -p "$INITRAMFS_PATH"

echo "- Cleaning ./target path"
sleep 0.5

sudo rm -rf $TARGET_PATH
mkdir $TARGET_PATH

if [ "$VAR_KERNEL_MODULES_COMPILE" = 'y' ]; then
	echo "- Cleaning up modules kernel cache"
	sleep 0.5

	sudo rm -rf $MODPROBE_COMPILED_DIR
	mkdir -p $MODPROBE_COMPILED_DIR
fi

echo "[cleanup] Cleanup is done"
