#! /bin/sh
set -euo pipefail

echo "[package-initramfs] Starting packaging ./initramfs"
sleep 0.5

echo "- ./initramfs path: '$ROOTFS_PATH'"
sleep 0.5

echo "- ./target path: '$TARGET_PATH'"
sleep 0.5

echo "- Umounting lazy partitions (this will be mounted in qemu)"
sleep 0.5

for fs in proc sys dev; do
  mountpoint -q "$INITRAMFS_PATH/$fs" && sudo umount -l "$INITRAMFS_PATH/$fs"
done

echo "- Compressing ./initramfs into initramfs.cpio.gz file"
sleep 0.5

cd $INITRAMFS_PATH
sudo find . | cpio -o -H newc | xz -T0 -z -C crc32 -6 > $TARGET_PATH/initramfs.cpio.xz

echo "[package-initramfs] ./initramfs has been compressed successfully"
sleep 0.5
