#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Instalar paquetes básicos '$INITRAMFS_INSTALLER_DIR'"
new_line

doas /sbin/apk --root $INITRAMFS_INSTALLER_DIR \
  --repositories-file /dev/null \
  --repository "http://os.wolfbear.mx/1.0/aarch64/apk" \
  add \
    apk-tools \
    shadow \
    dhcpcd \
    openresolv \
    util-linux \
    strace \
    openssh \
    grub-efi \
    parted \
    e2fsprogs \
    e2fsprogs-extra \
    dosfstools \
    rsync \
    nano \
    libc-utils

log_message $SCRIPT_NAME "Instalación de paquetes básicos terminada"
