#! /bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

echo "Descargando dependencias de terceros"

rm -Rf $WOLFBEAR_OS_DIR/dependencies/busybox
rm -Rf $WOLFBEAR_OS_DIR/dependencies/linux

mkdir -p $WOLFBEAR_OS_DIR/dependencies/busybox
mkdir -p $WOLFBEAR_OS_DIR/dependencies/linux

wget -O $WOLFBEAR_OS_DIR/dependencies/linux/wolfbear-kernel_aarch64.zip \
  "http://os.wolfbear.mx/1.0/kernel/aarch64/wolfbear-kernel_aarch64"

wget -O $WOLFBEAR_OS_DIR/dependencies/busybox/busybox_aarch64.zip \
  "http://os.wolfbear.mx/1.0/kernel/aarch64/busybox_aarch64.zip"

echo "Iniciando descompresión de dependencias"

cd $WOLFBEAR_OS_DIR/dependencies/busybox
unzip busybox_aarch64.zip

cd $WOLFBEAR_OS_DIR/dependencies/linux

echo "Descarga y descompresión de dependencias completada"