#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Sincronizando compilado de Busybox"
log_message $SCRIPT_NAME "desde '$DEPENDENCY_BUSYBOX_COMPILED_DIR' hasta '$INITRAMFS_DIR'"

rsync -a --links "$DEPENDENCY_BUSYBOX_COMPILED_DIR/" "$INITRAMFS_DIR/"

log_message $SCRIPT_NAME "Busybox ha sido sincronizado hacia $INITRAMFS_DIR"
