#!/bin/sh
set -euo pipefail
source $SCRIPTS_DIR/util-log

SCRIPT_NAME=$0

log_message $SCRIPT_NAME "Empaquetando archivos initramfs '$INITRAMFS_INSTALLER_DIR' y '$INITRAMFS_LAUNCHER_DIR'"

debug_message $SCRIPT_NAME "Desmontando posibles particiones del sistema que pudiesen estar en el directorio"

for fs in proc sys dev; do
  mountpoint -q "$INITRAMFS_INSTALLER_DIR/$fs" && doas umount -l "$INITRAMFS_INSTALLER_DIR/$fs"
done

debug_message $SCRIPT_NAME "Accediendo al directorio '$INITRAMFS_INSTALLER_DIR'"
cd $INITRAMFS_INSTALLER_DIR

debug_message $SCRIPT_NAME "Empaquetando el directorio '$INITRAMFS_INSTALLER_DIR'"

# movemos temporalmente el archivo init.install para que sea el principal y le respetamos sus permisos
mv init.install init
chmod +x init

# despues procedemos a comprimirlo
doas find . | cpio -o -H newc | xz -T0 -z -C crc32 -6 > $TARGET_DIR/initramfs.in.cpio.xz

# le regresamos su nombre y ahora movemos el init.launch para el init del sistema ya instalado
mv init init.install
mv init.launch init
chmod +x init

# luego procedemos a comprimirlo al igual que el initramfs anterior pero con otro nombre
doas find . | cpio -o -H newc | xz -T0 -z -C crc32 -6 > $TARGET_DIR/initramfs.la.cpio.xz

# regresamos el nombre del init a como estaba
mv init init.launch

log_message $SCRIPT_NAME "Empaquetado de archivos initramfs exitosamente"
