#!/bin/sh

QT_DIR="/usr/lib/qt6"

export QML2_IMPORT_PATH=/usr/lib/qt6/qml

log_message $SCRIPT_NAME "Construyendo wolfbear-apps"
debug_message $SCRIPT_NAME "qt-arm64 dir: '$QT_DIR'"

if [ ! -d "$DEPENDENCY_WOLFBEAR_APPS_DIR" ] || [ -z "$(ls -A "$DEPENDENCY_WOLFBEAR_APPS_DIR")" ]; then
	log_message $SCRIPT_NAME "La dependencia de wolfbear-apps no se encontró en el sistema"
	log_message $SCRIPT_NAME "por lo tanto será descargada desde su repositorio oficial"
	new_line

	git clone git@github.com:samsalra007/wolfbear-apps.git $DEPENDENCY_WOLFBEAR_APPS_DIR

	log_message $SCRIPT_NAME "La dependencia de wolfbear-apps se ha descargado exitosamente"
else 
	log_message $SCRIPT_NAME "No es necesario descargar wolfbear-apps ya que fue encontrado en la carpeta de dependencias"
fi

debug_message $SCRIPT_NAME "Abriendo directorio de '$DEPENDENCY_WOLFBEAR_APPS_DIR'"
cd $DEPENDENCY_WOLFBEAR_APPS_DIR

debug_message $SCRIPT_NAME "Obteniendo últimos cambios de '$DEPENDENCY_WOLFBEAR_APPS_DIR'"
git pull origin main

debug_message $SCRIPT_NAME "Limpiando directorio de compilación build"

rm -rf $DEPENDENCY_WOLFBEAR_APPS_DIR/build
mkdir -p $DEPENDENCY_WOLFBEAR_APPS_DIR/build

debug_message $SCRIPT_NAME "Abriendo directorio de compilación build"
cd $DEPENDENCY_WOLFBEAR_APPS_DIR/build

debug_message $SCRIPT_NAME "Compilando Launcher en $DEPENDENCY_WOLFBEAR_APPS_DIR/Launcher"

cmake $DEPENDENCY_WOLFBEAR_APPS_DIR/Launcher -DCMAKE_PREFIX_PATH=$QT_DIR
make -j$(nproc)

debug_message $SCRIPT_NAME "Eliminando antigua aplicación de Launcher"

rm -rf $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp.d
mkdir -p $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp.d
rm -f $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp.zip

debug_message $SCRIPT_NAME "Accediendo al directorio $DEPENDENCY_WOLFBEAR_APPS_DIR/build"
cd $DEPENDENCY_WOLFBEAR_APPS_DIR/build

debug_message $SCRIPT_NAME "Comprimiendo el directorio $( pwd ) hacia $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp"
zip -r $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp .

debug_message $SCRIPT_NAME "Desempaquetando en sys-apps 'OVERLAY_SYSAPPS_DIR'"
unzip $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp.zip -d $OVERLAY_SYSAPPS_DIR/apps/wolfbear-apps/LauncherApp.d