#!/bin/sh
set -euo pipefail
source "$SCRIPTS_DIR/util-log"

SCRIPT_NAME=$0
log_message $SCRIPT_NAME "Compilación del plugin EGLFS_KMS (libqeglfs-kms-integration.so) para Qt"

QT_VERSION_FULL="6.8.3"
QT_SRC_TAR="qt-everywhere-src-$QT_VERSION_FULL.tar.xz"
QT_SRC_URL="https://download.qt.io/archive/qt/6.8/$QT_VERSION_FULL/single/$QT_SRC_TAR"
QT_SRC_DIR="$DEPENDENCY_QT_PLUGIN_KMS/qt-everywhere-src-$QT_VERSION_FULL"
QT_BUILD_DIR="$QT_SRC_DIR/build"
PLUGIN_TARGET_DIR="$OVERLAY_SYSAPPS_DIR/usr/lib/qt6/plugins/eglfs_kms"

if [ ! -d "$QT_SRC_DIR" ]; then
	log_message $SCRIPT_NAME "Descargando Qt $QT_VERSION_FULL desde $QT_SRC_URL"
	mkdir -p "$DEPENDENCY_QT_PLUGIN_KMS"
	cd "$DEPENDENCY_QT_PLUGIN_KMS"

	if ! wget "$QT_SRC_URL"; then
		log_message $SCRIPT_NAME "[ERROR] Falló la descarga de $QT_SRC_TAR"
		exit 1
	fi

	tar xf "$QT_SRC_TAR"
else
	log_message $SCRIPT_NAME "Qt $QT_VERSION_FULL ya está descomprimido en $QT_SRC_DIR"
fi

log_message $SCRIPT_NAME "Limpiando carpeta build y accediendo en ella"
new_line

rm -rf "$QT_BUILD_DIR"
mkdir -p "$QT_BUILD_DIR"
cd "$QT_BUILD_DIR"

log_message $SCRIPT_NAME "Compilando qtbase"
cmake ../qtbase -GNinja \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_PREFIX_PATH=/usr/lib/qt6/cmake \
  -DQT_BUILD_EXAMPLES=OFF \
  -DQT_BUILD_TESTS=OFF

ninja

PLUGIN_SO=$(find . -name libqeglfs-kms-integration.so | head -n 1)

echo "PLUGIN SO: "
echo $PLUGIN_SO
