#!/bin/sh
set -euo pipefail

echo "Definiendo variables de directorios"

export SYS_ARCH=$(uname -m)
if [ "$SYS_ARCH" = 'aarch64' ] || [ "$SYS_ARCH" = 'arm64' ]; then
	SYS_ARCH='arm64'
else 
	SYS_ARCH='amd64'
fi

export VERSION_LINUX_KERNEL=6.12
export BUSY_BOX_VERSION=1.37.0
export QT_VERSION=6.8.3

export WOLFBEAR_OS_DIR="$(cd "$(dirname "$0")/.." && pwd)"

export SCRIPTS_DIR="$WOLFBEAR_OS_DIR/build.d"

export TARGET_DIR="$WOLFBEAR_OS_DIR/target"
export PATCHES_DIR="$WOLFBEAR_OS_DIR/patches"
export CONFIG_FILES_DIR="$WOLFBEAR_OS_DIR/config"
export INITRAMFS_DIR="$WOLFBEAR_OS_DIR/initramfs"

export DEPENDENCIES_DIR="$WOLFBEAR_OS_DIR/dependencies"
export DEPENDENCY_LINUX_DIR="$DEPENDENCIES_DIR/linux"
export DEPENDENCIES_LINUX_MODULES_DIR="$DEPENDENCIES_DIR/linux-modules"
export DEPENDENCY_BUSYBOX_DIR="$DEPENDENCIES_DIR/busybox-$BUSY_BOX_VERSION"
export DEPENDENCY_BUSYBOX_COMPILED_DIR="$DEPENDENCIES_DIR/busybox-compiled"
export DEPENDENCY_WOLFBEAR_APPS_DIR="$DEPENDENCIES_DIR/wolfbear-apps"
export DEPENDENCY_QT_PLUGIN_KMS="$DEPENDENCIES_DIR/qt-kms"

export OVERLAY_DIR="$WOLFBEAR_OS_DIR/overlay"
export OVERLAY_INITRAMFS_DIR="$OVERLAY_DIR/initramfs"
export OVERLAY_ROOTFS_DIR="$OVERLAY_DIR/rootfs"
export OVERLAY_SYSAPPS_DIR="$OVERLAY_DIR/sys-apps"
