#!/bin/sh
set -euo pipefail

SCRIPT_NAME=$0

export CURRENT_PATH="$(pwd)"
export SCRIPTS_DIR="$(dirname "$0")"

doas echo "Compilación de WolfbearOS en initramfs ha empezado"

# Ruta base del proyecto
BASEDIR="$(cd "$(dirname "$0")" && pwd)"

# Cargar variables globales
. "$BASEDIR/globals-definitions"

echo "$WOLFBEAR_OS_DIR en run"

# Ejecutar solo un script si se pasa por argumento
if [ -n "${1-}" ]; then
  SCRIPT_NAME_TO_EXECUTE="$1"
  echo "Has solicitado ejecutar el script '$SCRIPT_NAME_TO_EXECUTE'."
  sh "$SCRIPT_NAME_TO_EXECUTE"
  exit 0
fi

echo "Has solicitado ejecutar todos los scripts del directorio."
echo "scripts dir $SCRIPTS_DIR"
i=0
while :; do
  prefix=$(printf "%03d" "$i")
  found_any=false

  for script in "$SCRIPTS_DIR/${prefix}-"*; do
    [ -f "$script" ] || continue
    found_any=true

    if [ ! -x "$script" ]; then
      echo "Saltando script $script (no es ejecutable)"
      continue
    fi

    echo
    echo "Corriendo script $script"
    script_name="$(basename "$script")"

    if echo "$script_name" | grep -qE '^[0-9]{3}-doas-'; then
      echo "→ Este script requiere permisos de superusuario (doas)"
      doas sh -c ". \"$SCRIPTS_DIR/globals-definitions\" && sh \"$script\""
    else
      . "$script"
    fi
  done

  if [ "$found_any" = false ]; then
    echo
    echo "Se ha terminado la ejecución de los scripts (ya no existe el script ${prefix}-*)"
    break
  fi

  i=$((i + 1))
done

echo "Compilación de WolfbearOS ha terminado"
exit 0
