#!/bin/sh

set -euo pipefail

source ./globals

echo "Cleaning previous dependencies for disk image"
rm -rf "$LINUX_KERNEL_DEPENDENCY_DIR"
rm -rf "$BUSYBOX_DEPENDENCY_DIR"

echo "Creating dependency directories for disk image"
mkdir -p "$LINUX_KERNEL_DEPENDENCY_DIR"
mkdir -p "$BUSYBOX_DEPENDENCY_DIR"