#!/bin/sh

set -euo pipefail

source ./globals

echo "Cleaning previous dependencies for disk image"
rm -rf "$DISK_IMAGE_OUTPUT_DIR"

echo "Creating dependency directories for disk image"
mkdir -p "$DISK_IMAGE_OUTPUT_DIR"